import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Use | AI Case Calculator',
  description: 'Terms of use for the AI Case Calculator service.',
};

export default function TermsOfUse() {
  return (
    <div className="container" style={{ maxWidth: '800px' }}>
      <div className="card">
        <h1 style={{ fontSize: '28px', marginBottom: '8px' }}>Terms of Use</h1>
        <p style={{ color: 'var(--gray-500)', marginBottom: '32px' }}>
          Last Updated: May 12, 2026
        </p>

        <div style={{ lineHeight: '1.8', color: 'var(--gray-700)' }}>
          <section style={{ marginBottom: '32px' }}>
            <h2 style={{ fontSize: '20px', marginBottom: '12px' }}>1. Acceptance of Terms</h2>
            <p>
              By accessing or using the AI Case Calculator (&quot;Service&quot;), you agree to be bound 
              by these Terms of Use. If you do not agree to these terms, do not use the Service.
            </p>
          </section>

          <section style={{ marginBottom: '32px' }}>
            <h2 style={{ fontSize: '20px', marginBottom: '12px' }}>2. Service Description</h2>
            <p>
              The AI Case Calculator provides <strong>illustrative estimates</strong> of potential 
              personal injury claim values for educational purposes. The Service uses publicly 
              available data and standard estimation frameworks to generate ranges.
            </p>
          </section>

          <section style={{ marginBottom: '32px', background: '#fef3c7', padding: '20px', borderRadius: '8px', border: '1px solid #f59e0b' }}>
            <h2 style={{ fontSize: '20px', marginBottom: '12px', color: '#92400e' }}>
              3. IMPORTANT DISCLAIMERS
            </h2>
            
            <h3 style={{ fontSize: '16px', marginTop: '16px', marginBottom: '8px', color: '#92400e' }}>
              3.1 Not Legal Advice
            </h3>
            <p>
              <strong>THE SERVICE DOES NOT PROVIDE LEGAL ADVICE.</strong> The estimates provided 
              are for informational and educational purposes only. They do not constitute legal 
              advice, and no attorney-client relationship is created by using this Service.
            </p>

            <h3 style={{ fontSize: '16px', marginTop: '16px', marginBottom: '8px', color: '#92400e' }}>
              3.2 No Guarantee of Results
            </h3>
            <p>
              <strong>THE ESTIMATES ARE ILLUSTRATIVE ONLY AND DO NOT PREDICT ACTUAL OUTCOMES.</strong> 
              {' '}Real case values vary significantly based on specific facts, evidence, jurisdiction, 
              insurance coverage, and many other factors. Past results do not guarantee future outcomes.
            </p>

            <h3 style={{ fontSize: '16px', marginTop: '16px', marginBottom: '8px', color: '#92400e' }}>
              3.3 Consult an Attorney
            </h3>
            <p>
              You should consult with a qualified attorney for advice specific to your situation 
              before making any decisions about your legal rights or potential claims.
            </p>
          </section>

          <section style={{ marginBottom: '32px' }}>
            <h2 style={{ fontSize: '20px', marginBottom: '12px' }}>4. Methodology Disclosure</h2>
            <p>
              The estimates generated by this Service are based on:
            </p>
            <ul style={{ marginLeft: '20px', marginTop: '8px' }}>
              <li>
                Publicly available industry data from sources including the Insurance Information 
                Institute, FMCSA, and legal information resources
              </li>
              <li>
                Standard estimation frameworks such as the multiplier method for pain and suffering
              </li>
              <li>
                Explicitly disclosed assumptions (such as illustrative attorney fee rates)
              </li>
            </ul>
            <p style={{ marginTop: '12px' }}>
              Full source citations are provided with each estimate. Visit our{' '}
              <a href="/sources" style={{ color: 'var(--primary)' }}>Data Sources</a> page for 
              complete methodology details.
            </p>
          </section>

          <section style={{ marginBottom: '32px' }}>
            <h2 style={{ fontSize: '20px', marginBottom: '12px' }}>5. User Responsibilities</h2>
            <p>You agree to:</p>
            <ul style={{ marginLeft: '20px', marginTop: '8px' }}>
              <li>Provide accurate and truthful information when using the Service</li>
              <li>Use the Service only for lawful purposes</li>
              <li>Not attempt to manipulate or abuse the Service</li>
              <li>Not use automated means to access the Service without permission</li>
            </ul>
          </section>

          <section style={{ marginBottom: '32px' }}>
            <h2 style={{ fontSize: '20px', marginBottom: '12px' }}>6. Communications Consent</h2>
            <p>
              By submitting your contact information through the Service, you expressly consent to:
            </p>
            <ul style={{ marginLeft: '20px', marginTop: '8px' }}>
              <li>
                Receive telephone calls and text messages, including via automated technology, 
                from us and our partners for marketing purposes
              </li>
              <li>
                Receive communications at any time, including before 8am or after 9pm local time
              </li>
            </ul>
            <p style={{ marginTop: '12px' }}>
              Consent is not a condition of purchase or receiving services. Standard message and 
              data rates may apply. You may opt out at any time.
            </p>
          </section>

          <section style={{ marginBottom: '32px' }}>
            <h2 style={{ fontSize: '20px', marginBottom: '12px' }}>7. Intellectual Property</h2>
            <p>
              The Service, including its design, text, graphics, and code, is owned by us and 
              protected by copyright and other intellectual property laws. You may not copy, 
              modify, distribute, or create derivative works without our written permission.
            </p>
          </section>

          <section style={{ marginBottom: '32px' }}>
            <h2 style={{ fontSize: '20px', marginBottom: '12px' }}>8. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, 
              INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF 
              THE SERVICE.
            </p>
            <p style={{ marginTop: '12px' }}>
              WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR COMPLETELY 
              SECURE. THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND.
            </p>
          </section>

          <section style={{ marginBottom: '32px' }}>
            <h2 style={{ fontSize: '20px', marginBottom: '12px' }}>9. Indemnification</h2>
            <p>
              You agree to indemnify and hold us harmless from any claims, damages, or expenses 
              arising from your use of the Service or violation of these Terms.
            </p>
          </section>

          <section style={{ marginBottom: '32px' }}>
            <h2 style={{ fontSize: '20px', marginBottom: '12px' }}>10. Modifications</h2>
            <p>
              We reserve the right to modify these Terms at any time. Changes will be effective 
              upon posting to this page. Your continued use of the Service constitutes acceptance 
              of the modified Terms.
            </p>
          </section>

          <section style={{ marginBottom: '32px' }}>
            <h2 style={{ fontSize: '20px', marginBottom: '12px' }}>11. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the 
              State of [Your State], without regard to conflict of law principles.
            </p>
          </section>

          <section style={{ marginBottom: '32px' }}>
            <h2 style={{ fontSize: '20px', marginBottom: '12px' }}>12. Contact Information</h2>
            <p>
              For questions about these Terms, contact us at:
            </p>
            <ul style={{ marginLeft: '20px', marginTop: '8px', listStyle: 'none' }}>
              <li>Email: legal@[your-domain].com</li>
              <li>Phone: (833) 312-4023</li>
            </ul>
          </section>
        </div>

        <div style={{ marginTop: '32px', paddingTop: '24px', borderTop: '1px solid var(--gray-200)' }}>
          <a href="/" style={{ color: 'var(--primary)', textDecoration: 'none' }}>
            ← Back to Calculator
          </a>
        </div>
      </div>
    </div>
  );
}
