'use client';

import React, { useState } from 'react';

interface FAQItem {
  question: string;
  answer: React.ReactNode;
}

const FAQ_ITEMS: FAQItem[] = [
  {
    question: 'How does the AI Case Calculator function?',
    answer: (
      <>
        <p>
          Our exclusive AI Case Calculator is designed to give car crash victims an early look at their claim&apos;s 
          potential worth before they engage with insurers or attorneys. By completing a brief questionnaire about 
          your collision, you get an immediate valuation generated by artificial intelligence and historical settlement figures.
        </p>
        <p>
          The system has analyzed thousands of actual cases to match your situation and forecast a realistic settlement 
          bracket. This empowers you with the knowledge to recognize and reject inadequate settlement offers. Within moments, 
          you gain objective insights into the factors influencing your payout and can even be matched with vetted legal 
          professionals for tailored guidance.
        </p>
      </>
    ),
  },
  {
    question: 'What types of damages am I eligible to claim?',
    answer: (
      <>
        <p>
          A proper settlement should compensate you for both your financial burdens and your personal suffering. 
          Overlooking any of these areas means leaving money behind.
        </p>
        <p><strong>Financial (Economic) Damages:</strong></p>
        <ul>
          <li>Past and future medical expenses (including rehab and prescriptions)</li>
          <li>Lost income during your recovery period</li>
          <li>Decreased future earning capacity if injuries permanently impact your ability to work</li>
          <li>Costs to repair or replace your vehicle</li>
          <li>Diminished value (the drop in your vehicle&apos;s resale value, even after repairs)</li>
          <li>Everyday out-of-pocket costs, like travel to medical appointments or hiring in-home help</li>
        </ul>
        <p><strong>Personal (Non-Economic) Damages:</strong></p>
        <ul>
          <li>Physical pain and suffering</li>
          <li>Psychological trauma or emotional distress</li>
          <li>Inability to enjoy normal life activities</li>
          <li>Permanent disfigurement or scarring</li>
          <li>Loss of companionship or strain on family relationships</li>
        </ul>
        <p>
          We don&apos;t just estimate your claim&apos;s maximum value; we also guide you through the steps to secure it, 
          including linking you to experienced legal resources.
        </p>
      </>
    ),
  },
  {
    question: 'Should I rely on the insurance company to manage my claim?',
    answer: (
      <>
        <p>
          It is important to remember that insurance carriers operate to protect their bottom line, which often means 
          minimizing payouts. If you navigate the process alone, you risk:
        </p>
        <ul>
          <li>Getting paid only for immediate, obvious expenses while ignoring long-term costs</li>
          <li>Settling for a lowball offer before knowing the full medical extent of your injuries</li>
          <li>Having your pain, suffering, and future life impact severely undervalued</li>
          <li>Completely missing out on claims for diminished vehicle value</li>
        </ul>
        <p>
          Our complimentary platform ensures every single expense and loss is documented and backed by evidence, 
          helping you stand firm against tactics meant to underpay you.
        </p>
      </>
    ),
  },
  {
    question: 'Should I consult an attorney after a crash?',
    answer: (
      <>
        <p>
          An auto accident attorney specializes in navigating the maze of insurance claims, stepping in when insurers 
          try to deny or lowball your payout. They are especially crucial in personal injury scenarios where securing 
          comprehensive compensation for medical care and lost wages is the priority.
        </p>
        <p><strong>An attorney helps by:</strong></p>
        <ul>
          <li><strong>Leveling the playing field:</strong> You gain professional representation to face off against massive corporate legal teams.</li>
          <li><strong>Maximizing your payout:</strong> They fight to include all damages, especially future medical needs that adjusters often ignore.</li>
          <li><strong>Addressing underpaid or denied claims:</strong> They will investigate the reasons for a denial and advocate for your rightful funds.</li>
          <li><strong>Handling negotiations:</strong> They take over the back-and-forth, holding insurers accountable for fair practices and fighting &quot;bad faith&quot; tactics.</li>
          <li><strong>Taking cases to court:</strong> If a fair agreement isn&apos;t reached, they can file a civil lawsuit on your behalf.</li>
          <li><strong>Deciphering policy jargon:</strong> They understand complex insurance laws to build a watertight case.</li>
        </ul>
        <p>
          Keep in mind that initial consultations with local accident attorneys are usually free for qualifying individuals, 
          and there is no obligation to hire them if it doesn&apos;t feel right.
        </p>
      </>
    ),
  },
  {
    question: 'How long does it take to settle a claim and get paid?',
    answer: (
      <>
        <p>
          The timeframe fluctuates depending on the severity of injuries, liability arguments, and how cooperative 
          the insurance companies are.
        </p>
        <p><strong>Straightforward Claims (1–3 months):</strong></p>
        <ul>
          <li>Usually involves minor injuries or just property damage.</li>
          <li>Delays are minor, often related to getting repair estimates, inspections, or processing paperwork.</li>
        </ul>
        <p><strong>Complex Injury Claims (3–12+ months):</strong></p>
        <ul>
          <li>Timeframes stretch out because you must wait until you reach &quot;maximum medical improvement&quot; to accurately calculate total medical costs.</li>
        </ul>
        <p><strong>Frequent Causes for Delay:</strong></p>
        <ul>
          <li>Missing or slow paperwork</li>
          <li>Disagreements over who caused the crash</li>
          <li>Ongoing medical treatments</li>
          <li>Intentional stalling by the insurance adjuster</li>
          <li>Waiting on specialist evaluations or surgeries</li>
        </ul>
        <p>
          <strong>How to speed things up:</strong> Finish all medical treatments before agreeing to a settlement, 
          submit your documentation quickly and in an organized fashion, and consider hiring a lawyer to keep the process moving.
        </p>
      </>
    ),
  },
  {
    question: 'Is a police report mandatory to file my insurance claim?',
    answer: (
      <>
        <p>
          While not technically required to initiate a claim, possessing the official accident report heavily streamlines 
          the process and guards against future disputes.
        </p>
        <p><strong>You can usually file without it if:</strong></p>
        <ul>
          <li>The crash was very recent and you are just opening the file</li>
          <li>Fault is mutually agreed upon</li>
          <li>Injuries or damages are minor</li>
        </ul>
        <p><strong>It becomes absolutely necessary when:</strong></p>
        <ul>
          <li>The at-fault driver changes their story or fault is disputed</li>
          <li>Injuries show up days later</li>
          <li>You are asking for compensation beyond basic vehicle repairs (like medical bills)</li>
          <li>You are the victim of a hit-and-run or an uninsured driver</li>
          <li>The situation might escalate into a lawsuit</li>
        </ul>
        <p>
          Insurance adjusters lean heavily on police reports as an unbiased, third-party record of the event, confirming 
          the time, location, and witnesses. Lacking one gives insurers a reason to question your claim. We can assist you 
          in obtaining your report and connecting you with legal resources before you officially file.
        </p>
      </>
    ),
  },
  {
    question: 'How can I file a diminished value claim for my vehicle?',
    answer: (
      <>
        <p>
          Many drivers are unaware they are entitled to diminished value compensation, and insurance companies will 
          rarely offer it voluntarily. Here is how to pursue it:
        </p>
        <ol>
          <li><strong>Check your state laws:</strong> Regulations change depending on your location. Some states explicitly allow these claims, while others restrict or prohibit them. We can help you check your local laws.</li>
          <li><strong>Settle property damage first:</strong> Wait until your vehicle is fully repaired. Keep all receipts and invoices safe.</li>
          <li><strong>Compile evidence of lost value:</strong> Gather your repair bills, proof of the car&apos;s pre-crash value (based on mileage and condition), post-repair appraisals from trusted sources, and photos of the damage.</li>
          <li><strong>Calculate the exact loss:</strong> Utilize professional appraisals, market comparisons, or industry-standard formulas (like the 17c method) to find the monetary drop in value.</li>
          <li><strong>Send a formal demand:</strong> Submit your evidence and a formal request for compensation to the at-fault driver&apos;s insurance provider.</li>
          <li><strong>Fight back against pushback:</strong> Insurers commonly argue your car is too old, has too many miles, or that repairs restored its full value. Professional support is key here.</li>
        </ol>
        <p><strong>Factors that strengthen a diminished value claim:</strong></p>
        <ul>
          <li>Newer or low-mileage vehicles</li>
          <li>Repairs completed at highly reputable shops</li>
          <li>Structural or heavy damage</li>
          <li>Vehicle models that traditionally hold strong resale value</li>
        </ul>
      </>
    ),
  },
  {
    question: 'What should I do immediately following a car crash?',
    answer: (
      <>
        <p>
          Taking the right actions can make a massive difference in your future claim. Follow this checklist:
        </p>
        <ol>
          <li><strong>Prioritize Safety:</strong> Move to a safe location if possible. Activate your hazard lights and set up warning triangles or flares.</li>
          <li><strong>Contact the Authorities:</strong> Dial 911 if there are injuries or severe damage. Report the accident and always request the responding officer&apos;s name and badge number.</li>
          <li><strong>Swap Details:</strong> Trade names, contact info, insurance details, and license plate numbers with the other involved driver(s). Grab contact information from any witnesses.</li>
          <li><strong>Gather Evidence:</strong> Photograph the entire scene, including vehicle damage, license plates, road conditions, and weather.</li>
          <li><strong>Get an Official Record:</strong> If police do not arrive at the scene, visit the nearest station to file a report yourself.</li>
          <li><strong>Reach Out to Us:</strong> We can guide you step-by-step through the entire process to ensure you are positioned for the maximum possible compensation.</li>
        </ol>
      </>
    ),
  },
];

export function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const toggleItem = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <div className="faq-section">
      <h2>Frequently Asked Questions</h2>
      <div className="faq-list">
        {FAQ_ITEMS.map((item, index) => (
          <div key={index} className={`faq-item ${openIndex === index ? 'open' : ''}`}>
            <button 
              className="faq-question" 
              onClick={() => toggleItem(index)}
              aria-expanded={openIndex === index}
            >
              {item.question}
              <span className="faq-icon">{openIndex === index ? '−' : '+'}</span>
            </button>
            {openIndex === index && (
              <div className="faq-answer">
                {item.answer}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
